# Generated by Django 2.1.2 on 2018-11-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='Enter Category name', max_length=20, unique=True, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='EthnicFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnic_food_name', models.CharField(help_text='Enter ethnic food name', max_length=20, unique=True, verbose_name='Ethnic food')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='Enter food name', max_length=20, unique=True, verbose_name='Food name')),
                ('image_location', models.CharField(blank=True, help_text='Enter url location', max_length=100, null=True, unique=True, verbose_name='Image url')),
                ('average_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Average price')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Rate')),
                ('category', models.ManyToManyField(to='khubkhaoapp.Category', verbose_name='Category')),
                ('ethnic_food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khubkhaoapp.EthnicFood', verbose_name='Ethnic Food')),
            ],
        ),
    ]
